import { useState, useEffect } from 'react';
import { FiX, FiCheck, FiInfo, FiTag, FiDollarSign, FiFileText, FiTarget, FiCalendar, FiShield, FiPlus } from 'react-icons/fi';
import api from '../api/axios';

const PARTNERSHIP_TYPES = ['financial', 'in-kind', 'skills-based', 'hybrid'];

export default function PartnershipFormModal({ onClose, onSave, initialCampaignId }) {
    const [campaigns, setCampaigns] = useState([]);
    const [fetching, setFetching] = useState(false);
    const [form, setForm] = useState({
        campaignId: initialCampaignId || '',
        title: '',
        partnershipType: 'financial', // maps to agreementType in backend
        totalValue: '',
        description: '',
        startDate: '',
        endDate: '',
        terms: 'I agree to the partnership terms and mission objectives.',
    });

    const [saving, setSaving] = useState(false);

    const [error, setError] = useState('');

    useEffect(() => {
        async function loadCampaigns() {
            setFetching(true);
            try {
                const res = await api.get('/api/campaigns');
                const list = Array.isArray(res.data) ? res.data : (res.data?.data || []);
                setCampaigns(list.filter(c => c.status === 'published' || c.status === 'active'));
            } catch (err) {
                console.error("Failed to load campaigns", err);
            } finally {
                setFetching(false);
            }
        }
        loadCampaigns();
    }, []);

    const [milestones, setMilestones] = useState([
        { title: 'Project Initiation', budget: '', dueDate: '', status: 'pending' }
    ]);
    const [autoMilestones, setAutoMilestones] = useState(true);

    const getAutoGeneratedPhases = () => {
        if (!form.startDate || !form.endDate || !form.totalValue) return [];
        const start = new Date(form.startDate);
        const end = new Date(form.endDate);
        const totalVal = Number(String(form.totalValue || '0').replace(/,/g, '')) || 0;
        const diffDays = Math.ceil((end - start) / (1000 * 60 * 60 * 24));
        if (diffDays <= 0) return [];

        const phases = [
            { title: 'Project Kickoff & Resource Planning', fraction: 0.1, valShare: 0.2 },
            { title: 'Main Execution Phase', fraction: 0.5, valShare: 0.5 },
            { title: 'Final Review & Handover', fraction: 0.9, valShare: 0.3 }
        ];

        let allocated = 0;
        const result = phases.map((p, i) => {
            const stepDate = new Date(start);
            stepDate.setDate(stepDate.getDate() + Math.floor(diffDays * p.fraction));
            
            let budget = Math.floor(totalVal * p.valShare);
            // On last milestone, take the remaining balance to ensure sum matches exactly
            if (i === phases.length - 1) {
                budget = totalVal - allocated;
            } else {
                allocated += budget;
            }

            return {
                title: p.title,
                budget,
                dueDate: stepDate.toISOString().split('T')[0],
                status: 'pending'
            };
        });
        return result;
    };

    const addMilestone = () => {
        setMilestones([...milestones, { title: '', budget: '', dueDate: '' }]);
        setAutoMilestones(false);
    };

    const removeMilestone = (index) => {
        setMilestones(milestones.filter((_, i) => i !== index));
    };

    const updateMilestone = (index, field, value) => {
        const updated = [...milestones];
        updated[index][field] = value;
        setMilestones(updated);
        setAutoMilestones(false);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!form.campaignId) return setError('Please select a campaign mission.');
        if (form.title.trim().length < 5) return setError('Agreement title must be at least 5 characters long.');
        if (!form.startDate || !form.endDate) return setError('Please select both start and end dates.');
        if (new Date(form.endDate) <= new Date(form.startDate)) return setError('Lifecycle End must be after Lifecycle Start.');
        if (!form.totalValue || Number(form.totalValue) <= 0) return setError('Please enter a valid amount.');
        
        setError('');
        
        // Use auto-generated phases if selected Hub
        const finalMilestones = autoMilestones ? getAutoGeneratedPhases() : milestones.map(m => ({
            ...m,
            budget: Number(m.budget) || 0,
            status: m.status || 'pending'
        }));

        // Validate milestones total equals agreement total
        const milestonesTotal = finalMilestones.reduce((sum, m) => sum + m.budget, 0);
        const agreementTotal = Number(String(form.totalValue || '0').replace(/,/g, ''));
        
        if (milestonesTotal !== agreementTotal) {
            return setError(`The sum of roadmap steps (LKR ${milestonesTotal.toLocaleString()}) must equal the total commitment (LKR ${agreementTotal.toLocaleString()}).`);
        }

        const payload = {
            campaignId: form.campaignId,
            title: form.title,
            description: form.description,
            agreementType: form.partnershipType,
            totalValue: Number(String(form.totalValue || '0').replace(/,/g, '')),
            startDate: form.startDate,
            endDate: form.endDate,
            terms: form.terms,
            initialMilestones: finalMilestones,
            milestones: finalMilestones
        };
        
        setSaving(true);
        try {
            await onSave(payload);
        } catch (err) {
            const backendError = err.response?.data;
            if (backendError?.errors?.[0]?.message) {
                setError(`${backendError.message}: ${backendError.errors[0].message}`);
            } else {
                setError(backendError?.message || err.message || 'Proposal initialization failure Hub.');
            }
            setSaving(false);
        }
    };

    const previewAuto = getAutoGeneratedPhases();

    return (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center z-[100] p-4 text-left">
            <div className="bg-white rounded-[40px] shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col animate-scaleIn">
                <div className="flex items-center justify-between p-8 border-b border-slate-50 shrink-0">
                    <div>
                        <p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-slate-400 mb-1">Mission Alliance Proposal</p>
                        <h3 className="text-2xl font-extrabold text-slate-900 tracking-tight ">Propose Partnership</h3>
                    </div>
                    <button onClick={onClose} className="w-12 h-12 flex items-center justify-center bg-slate-50 hover:bg-rose-50 rounded-2xl text-slate-400 hover:text-rose-500 transition-all active:scale-90">
                        <FiX className="text-xl" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-8 space-y-10 scrollbar-none">
                    {error && (
                        <div className="bg-red-50 border border-red-100 text-red-600 px-5 py-4 rounded-2xl text-[11px] font-extrabold uppercase tracking-widest flex items-center gap-3 animate-shake">
                           <FiInfo className="shrink-0" /> {error}
                        </div>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        {/* Title Field */ }
                        <div className="md:col-span-2 space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiFileText /> Agreement Title
                            </label>
                            <input 
                                type="text"
                                placeholder="e.g. 2024 Educational Support Alliance"
                                value={form.title}
                                onChange={e => setForm({...form, title: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-base font-extrabold text-slate-800 placeholder:text-slate-300 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all outline-none "
                            />
                        </div>

                        {/* Campaign Selection */}
                        <div className="md:col-span-2 space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiTarget /> Select Campaign Mission
                            </label>
                            <div className="relative">
                                <select 
                                    value={form.campaignId}
                                    disabled={!!initialCampaignId || fetching}
                                    onChange={e => setForm({...form, campaignId: e.target.value})}
                                    className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-extrabold text-slate-800 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all appearance-none cursor-pointer disabled:opacity-60 outline-none "
                                >
                                    <option value="">{fetching ? 'Loading missions...' : 'Choose a mission...'}</option>
                                    {campaigns.map(c => (
                                        <option key={c._id} value={c._id}>{c.title}</option>
                                    ))}
                                </select>
                                <div className="absolute right-5 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M19 9l-7 7-7-7"/></svg>
                                </div>
                            </div>
                        </div>

                        {/* Partnership Type */}
                        <div className="space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiTag /> Contribution Type
                            </label>
                            <select 
                                value={form.partnershipType}
                                onChange={e => setForm({...form, partnershipType: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-extrabold text-slate-800 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all appearance-none cursor-pointer outline-none "
                            >
                                {PARTNERSHIP_TYPES.map(t => <option key={t} value={t}>{t.charAt(0).toUpperCase() + t.slice(1)} Support</option>)}
                            </select>
                        </div>

                        {/* Amount */}
                        <div className="space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiDollarSign /> Total Commitment (LKR)
                            </label>
                            <input 
                                type="number"
                                placeholder="e.g. 500000"
                                value={form.totalValue}
                                onChange={e => setForm({...form, totalValue: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-extrabold text-slate-800 placeholder:text-slate-300 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all outline-none "
                            />
                        </div>

                        {/* Start Date */}
                        <div className="space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiCalendar /> Lifecycle Start
                            </label>
                            <input 
                                type="date"
                                value={form.startDate}
                                onChange={e => setForm({...form, startDate: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-extrabold text-slate-800 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all outline-none "
                            />
                        </div>

                        {/* End Date */}
                        <div className="space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiCalendar /> Lifecycle End
                            </label>
                            <input 
                                type="date"
                                value={form.endDate}
                                min={form.startDate}
                                onChange={e => setForm({...form, endDate: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-extrabold text-slate-800 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all outline-none "
                            />
                        </div>

                        {/* Success Steps Breakdown Section */}
                        <div className="md:col-span-2 pt-4 space-y-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <h4 className="text-sm font-extrabold text-slate-900 uppercase tracking-tight ">Success Steps Roadmap</h4>
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest  mt-1">Fragmentation registry for capital deployment hub.</p>
                                </div>
                                <div className="flex items-center gap-4">
                                    <label className="flex items-center gap-2 cursor-pointer group">
                                        <input 
                                            type="checkbox" 
                                            checked={autoMilestones}
                                            onChange={(e) => setAutoMilestones(e.target.checked)}
                                            className="w-4 h-4 rounded border-slate-300 text-tf-primary focus:ring-tf-primary"
                                        />
                                        <span className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-hover:text-tf-primary transition-colors ">Auto-Generate</span>
                                    </label>
                                    <button 
                                        type="button" 
                                        onClick={addMilestone}
                                        className="w-8 h-8 flex items-center justify-center bg-slate-900 text-white rounded-lg hover:bg-tf-primary transition-all active:scale-95 shadow-lg shadow-slate-900/10"
                                    >
                                        <FiPlus />
                                    </button>
                                </div>
                            </div>

                            {!autoMilestones && (
                                <div className="space-y-4 max-h-[300px] overflow-y-auto pr-4 scrollbar-thin">
                                   {milestones.map((ms, idx) => (
                                       <div key={idx} className="p-5 bg-slate-50 rounded-[2rem] border border-slate-100 space-y-4 relative group">
                                           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                               <div className="md:col-span-2">
                                                   <input 
                                                        placeholder="Phase Title (e.g. Phase 1 Initiation)"
                                                        value={ms.title}
                                                        onChange={(e) => updateMilestone(idx, 'title', e.target.value)}
                                                        className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold text-slate-800 focus:border-tf-primary outline-none transition-all "
                                                   />
                                               </div>
                                               <div>
                                                   <input 
                                                        type="number"
                                                        placeholder="Value (LKR)"
                                                        value={ms.budget}
                                                        onChange={(e) => updateMilestone(idx, 'budget', e.target.value)}
                                                        className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold text-slate-800 focus:border-tf-primary outline-none transition-all "
                                                   />
                                               </div>
                                               <div>
                                                   <input 
                                                        type="date"
                                                        value={ms.dueDate}
                                                        onChange={(e) => updateMilestone(idx, 'dueDate', e.target.value)}
                                                        className="w-full bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold text-slate-800 focus:border-tf-primary outline-none transition-all "
                                                   />
                                               </div>
                                           </div>
                                           {milestones.length > 1 && (
                                               <button 
                                                    type="button"
                                                    onClick={() => removeMilestone(idx)}
                                                    className="absolute -right-2 -top-2 w-7 h-7 bg-white text-rose-500 rounded-full border border-rose-100 shadow-sm flex items-center justify-center hover:bg-rose-50 transition-all opacity-0 group-hover:opacity-100"
                                               >
                                                   <FiX className="text-xs" />
                                               </button>
                                           )}
                                       </div>
                                   ))}
                                </div>
                            )}
                            
                            {autoMilestones && previewAuto.length > 0 ? (
                                <div className="space-y-3">
                                   <p className="text-[9px] font-extrabold uppercase tracking-[0.2em] text-tf-primary  px-2 mb-2">Live Institutional Auto-Preview Hub:</p>
                                   {previewAuto.map((p, idx) => (
                                       <div key={idx} className="flex items-center gap-4 p-4 bg-emerald-50/30 border border-emerald-100/50 rounded-2xl group transition-all hover:bg-white hover:shadow-lg">
                                           <div className="w-8 h-8 rounded-xl bg-tf-primary text-white flex items-center justify-center text-[10px] font-extrabold ">0{idx+1}</div>
                                           <div className="flex-1">
                                                <p className="text-[11px] font-extrabold text-slate-900  tracking-tight">{p.title}</p>
                                                <p className="text-[8px] font-extrabold text-slate-400 uppercase tracking-widest mt-0.5">{new Date(p.dueDate).toLocaleDateString()}</p>
                                           </div>
                                           <div className="text-right">
                                                <p className="text-[11px] font-extrabold text-tf-primary  tabular-nums">LKR {p.budget.toLocaleString()}</p>
                                           </div>
                                       </div>
                                   ))}
                                </div>
                            ) : autoMilestones && (
                                <div className="p-8 bg-slate-50/50 border border-dashed border-slate-200 rounded-[2rem] flex items-center justify-center text-center">
                                    <p className="text-[10px] font-extrabold uppercase tracking-widest text-slate-300 ">Define dates and amount to view auto-roadmap preview Hub.</p>
                                </div>
                            )}
                        </div>

                        {/* Terms checkbox */}
                        <div className="md:col-span-2 pt-6">
                             <label className="flex items-start gap-4 p-6 bg-slate-50 border border-slate-100 rounded-[2.5rem] cursor-pointer hover:bg-slate-100 transition-all group">
                                <div className="mt-1">
                                    <input 
                                      type="checkbox" 
                                      required 
                                      className="w-5 h-5 rounded-lg border-slate-300 text-tf-primary focus:ring-tf-primary"
                                    />
                                </div>
                                <div className="flex-1">
                                    <p className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 flex items-center gap-2 "><FiShield /> Institutional Terms & Protocol</p>
                                    <p className="text-xs font-bold text-slate-600 mt-1.5 leading-relaxed ">
                                        I confirm that the institutional data provided is accurate and I agree to fulfill the commitments specified in this mission alliance within the fragmented execution phases Hub.
                                    </p>
                                </div>
                             </label>
                        </div>

                        <div className="md:col-span-2 space-y-2 group">
                            <label className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 group-focus-within:text-tf-primary transition-colors flex items-center gap-1.5">
                                <FiFileText /> Strategic Notes
                            </label>
                            <textarea 
                                rows="3"
                                placeholder="Details about this strategic partnership..."
                                value={form.description}
                                onChange={e => setForm({...form, description: e.target.value})}
                                className="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-4 text-sm font-bold text-slate-800 placeholder:text-slate-300 focus:outline-none focus:ring-4 focus:ring-tf-primary/5 transition-all resize-none outline-none "
                            />
                        </div>
                    </div>
                </form>

                <div className="p-10 border-t border-slate-50 bg-slate-50/50 flex gap-4 shrink-0">
                    <button type="button" onClick={onClose} className="flex-1 px-8 py-5 bg-white border border-slate-200 text-slate-500 rounded-2xl text-[10px] font-extrabold uppercase tracking-widest hover:bg-slate-50 transition-all shadow-sm">
                        Cancel Registry
                    </button>
                    <button onClick={handleSubmit} disabled={fetching || saving} className="flex-[2] px-8 py-5 bg-tf-primary text-white rounded-2xl text-[10px] font-extrabold uppercase tracking-[0.2em] shadow-2xl shadow-tf-primary/30 transition-all flex items-center justify-center gap-3 active:scale-95 disabled:opacity-50 ">
                        {fetching || saving ? 'Synchronizing...' : 'Submit Mission Proposal'} <FiCheck className="text-lg stroke-[3]" />
                    </button>
                </div>
            </div>
            <style>{`
                @keyframes shake {
                    0%, 100% { transform: translateX(0); }
                    25% { transform: translateX(-4px); }
                    75% { transform: translateX(4px); }
                }
                .animate-shake {
                    animation: shake 0.2s ease-in-out 0s 2;
                }
            `}</style>
        </div>
    );
}
